module Ressources
{
	enum RessourceType 
	{
		WOOD, MARBLE, WINE, CRYSTAL, BRIMSTONE
	};

	interface Ressource
	{
		readonly attribute RessourceType type;
		readonly attribute long count;
		readonly attribute long step; 

		void pretype(in RessourceType type);
		void generate(in long count);
		boolean acquire(in long count);
	};
};
