package Producers;


/**
* Producers/RemoteProducerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
*/

abstract public class RemoteProducerHelper
{
  private static String  _id = "IDL:Producers/RemoteProducer:1.0";

  public static void insert (org.omg.CORBA.Any a, Producers.RemoteProducer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Producers.RemoteProducer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Producers.RemoteProducerHelper.id (), "RemoteProducer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Producers.RemoteProducer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemoteProducerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Producers.RemoteProducer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Producers.RemoteProducer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Producers.RemoteProducer)
      return (Producers.RemoteProducer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Producers._RemoteProducerStub stub = new Producers._RemoteProducerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Producers.RemoteProducer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Producers.RemoteProducer)
      return (Producers.RemoteProducer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Producers._RemoteProducerStub stub = new Producers._RemoteProducerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
