package Producers;


/**
* Producers/RemoteProducerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Piatok, 2017, apríla 28 16:52:56 CEST
*/

public interface RemoteProducerOperations 
{
  Producers.RessourceType type ();
  int id ();
  int count ();
  int step ();
  int refillFrequence ();
  boolean readyToGo ();
  void setReadyToGo (boolean status);
  void pretype (Producers.RessourceType type);
  void generate ();
  int acquire (int units, char personality);
} // interface RemoteProducerOperations
