package Producers;


/**
* Producers/RemoteProducerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
*/

public interface RemoteProducerOperations 
{
  Producers.RessourceType type ();
  int id ();
  int count ();
  int step ();
  int refillFrequence ();
  boolean readyToGo ();
  boolean infiniteRessources ();
  boolean empty ();
  void setReadyToGo (boolean status);
  void setInfiniteRessources (boolean property);
  void pretype (Producers.RessourceType type);
  void generate ();
  int acquire (int units, char personality);
  String _toString ();
} // interface RemoteProducerOperations
