package Producers;


/**
* Producers/RemoteProducer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Piatok, 2017, apríla 28 16:52:56 CEST
*/

public interface RemoteProducer extends RemoteProducerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteProducer
