package Producers;


/**
* Producers/RemoteProducerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Streda, 2017, apríla 26 11:20:56 CEST
*/

public interface RemoteProducerOperations 
{
  Producers.RessourceType type ();
  int id ();
  int count ();
  int step ();
  int refillFrequence ();
  void pretype (Producers.RessourceType type);
  void generate ();
  boolean acquire (int count);
} // interface RemoteProducerOperations
