package Producers;


/**
* Producers/RemoteProducer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Pondelok, 2017, mája 1 18:10:00 CEST
*/

public interface RemoteProducer extends RemoteProducerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteProducer
