package Producers;


/**
* Producers/RessourceTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Streda, 2017, apríla 26 11:20:56 CEST
*/

abstract public class RessourceTypeHelper
{
  private static String  _id = "IDL:Producers/RessourceType:1.0";

  public static void insert (org.omg.CORBA.Any a, Producers.RessourceType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Producers.RessourceType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (Producers.RessourceTypeHelper.id (), "RessourceType", new String[] { "WOOD", "MARBLE", "WINE", "CRYSTAL", "BRIMSTONE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Producers.RessourceType read (org.omg.CORBA.portable.InputStream istream)
  {
    return Producers.RessourceType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Producers.RessourceType value)
  {
    ostream.write_long (value.value ());
  }

}
