package Producers;


/**
* Producers/RessourceType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
* Streda, 2017, apríla 26 11:20:56 CEST
*/

public class RessourceType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static Producers.RessourceType[] __array = new Producers.RessourceType [__size];

  public static final int _WOOD = 0;
  public static final Producers.RessourceType WOOD = new Producers.RessourceType(_WOOD);
  public static final int _MARBLE = 1;
  public static final Producers.RessourceType MARBLE = new Producers.RessourceType(_MARBLE);
  public static final int _WINE = 2;
  public static final Producers.RessourceType WINE = new Producers.RessourceType(_WINE);
  public static final int _CRYSTAL = 3;
  public static final Producers.RessourceType CRYSTAL = new Producers.RessourceType(_CRYSTAL);
  public static final int _BRIMSTONE = 4;
  public static final Producers.RessourceType BRIMSTONE = new Producers.RessourceType(_BRIMSTONE);

  public int value ()
  {
    return __value;
  }

  public static Producers.RessourceType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RessourceType (int value)
  {
    __value = value;
    __array[__value] = this;
  }

  public static Producers.RessourceType[] values()
  {
    return __array;
  }
} // class RessourceType