package Producers;

/**
* Producers/RessourceTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
*/

public final class RessourceTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public Producers.RessourceType value = null;

  public RessourceTypeHolder ()
  {
  }

  public RessourceTypeHolder (Producers.RessourceType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Producers.RessourceTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Producers.RessourceTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Producers.RessourceTypeHelper.type ();
  }

}
