package Producers;


/**
* Producers/RessourceType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteProducer.idl
*/

public class RessourceType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static Producers.RessourceType[] __array = new Producers.RessourceType [__size];

  public static final int _WOOD = 0;
  public static final Producers.RessourceType WOOD = new Producers.RessourceType(_WOOD);
  public static final int _MARBLE = 1;
  public static final Producers.RessourceType MARBLE = new Producers.RessourceType(_MARBLE);

  public int value ()
  {
    return __value;
  }

  public static Producers.RessourceType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RessourceType (int value)
  {
    __value = value;
    __array[__value] = this;
  }

  public String toString()
  {
    switch (__value)
    {
      case 0:
        return "WOOD";
      case 1:
        return "MARBLE";
      default:
        return "(unknown)";
    }
  }
} // class RessourceType
