package Ressources;


/**
* Ressources/RessourceTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

abstract public class RessourceTypeHelper
{
  private static String  _id = "IDL:Ressources/RessourceType:1.0";

  public static void insert (org.omg.CORBA.Any a, Ressources.RessourceType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Ressources.RessourceType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (Ressources.RessourceTypeHelper.id (), "RessourceType", new String[] { "WOOD", "MARBLE", "WINE", "CRYSTAL", "BRIMSTONE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Ressources.RessourceType read (org.omg.CORBA.portable.InputStream istream)
  {
    return Ressources.RessourceType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Ressources.RessourceType value)
  {
    ostream.write_long (value.value ());
  }

}
