package Ressources;

/**
* Ressources/RessourceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Utorok, 2017, apríla 18 18:15:36 CEST
*/

public final class RessourceHolder implements org.omg.CORBA.portable.Streamable
{
  public Ressources.Ressource value = null;

  public RessourceHolder ()
  {
  }

  public RessourceHolder (Ressources.Ressource initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ressources.RessourceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ressources.RessourceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ressources.RessourceHelper.type ();
  }

}
