package Ressources;


/**
* Ressources/Ressource.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Utorok, 2017, apríla 18 18:15:36 CEST
*/

public interface Ressource extends RessourceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ressource
