package Ressources;


/**
* Ressources/RessourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Utorok, 2017, apríla 18 18:15:36 CEST
*/

public interface RessourceOperations 
{
  Ressources.RessourceType type ();
  int count ();
  int step ();
  void pretype (Ressources.RessourceType type);
  void generate ();
  boolean acquire (int count);
} // interface RessourceOperations
