package Consumers;


/**
* Consumers/__RessourceHolderImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Streda, 2017, apríla 26 11:26:04 CEST
*/

public abstract class __RessourceHolderImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Consumers._RessourceHolder, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public __RessourceHolderImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_resWood", new java.lang.Integer (0));
    _methods.put ("_get_resMarble", new java.lang.Integer (1));
    _methods.put ("_get_resWine", new java.lang.Integer (2));
    _methods.put ("_get_resCrystal", new java.lang.Integer (3));
    _methods.put ("_get_resBrimstone", new java.lang.Integer (4));
    _methods.put ("setWood", new java.lang.Integer (5));
    _methods.put ("setMarble", new java.lang.Integer (6));
    _methods.put ("setWine", new java.lang.Integer (7));
    _methods.put ("setCrystal", new java.lang.Integer (8));
    _methods.put ("setBrimstone", new java.lang.Integer (9));
    _methods.put ("setAll", new java.lang.Integer (10));
    _methods.put ("compare", new java.lang.Integer (11));
    _methods.put ("add", new java.lang.Integer (12));
    _methods.put ("addExplicit", new java.lang.Integer (13));
    _methods.put ("toString", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Consumers/_RessourceHolder/_get_resWood
       {
         int $result = (int)0;
         $result = this.resWood ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Consumers/_RessourceHolder/_get_resMarble
       {
         int $result = (int)0;
         $result = this.resMarble ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Consumers/_RessourceHolder/_get_resWine
       {
         int $result = (int)0;
         $result = this.resWine ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // Consumers/_RessourceHolder/_get_resCrystal
       {
         int $result = (int)0;
         $result = this.resCrystal ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // Consumers/_RessourceHolder/_get_resBrimstone
       {
         int $result = (int)0;
         $result = this.resBrimstone ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // Consumers/_RessourceHolder/setWood
       {
         int units = in.read_long ();
         this.setWood (units);
         out = $rh.createReply();
         break;
       }

       case 6:  // Consumers/_RessourceHolder/setMarble
       {
         int units = in.read_long ();
         this.setMarble (units);
         out = $rh.createReply();
         break;
       }

       case 7:  // Consumers/_RessourceHolder/setWine
       {
         int units = in.read_long ();
         this.setWine (units);
         out = $rh.createReply();
         break;
       }

       case 8:  // Consumers/_RessourceHolder/setCrystal
       {
         int units = in.read_long ();
         this.setCrystal (units);
         out = $rh.createReply();
         break;
       }

       case 9:  // Consumers/_RessourceHolder/setBrimstone
       {
         int units = in.read_long ();
         this.setBrimstone (units);
         out = $rh.createReply();
         break;
       }

       case 10:  // Consumers/_RessourceHolder/setAll
       {
         int uWood = in.read_long ();
         int uMarble = in.read_long ();
         int uWine = in.read_long ();
         int uCrytsal = in.read_long ();
         int uBrimstone = in.read_long ();
         this.setAll (uWood, uMarble, uWine, uCrytsal, uBrimstone);
         out = $rh.createReply();
         break;
       }

       case 11:  // Consumers/_RessourceHolder/compare
       {
         Consumers._RessourceHolder toBeCompared = Consumers._RessourceHolderHelper.read (in);
         int $result = (int)0;
         $result = this.compare (toBeCompared);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // Consumers/_RessourceHolder/add
       {
         Consumers._RessourceHolder operand = Consumers._RessourceHolderHelper.read (in);
         Consumers._RessourceHolder $result = null;
         $result = this.add (operand);
         out = $rh.createReply();
         Consumers._RessourceHolderHelper.write (out, $result);
         break;
       }

       case 13:  // Consumers/_RessourceHolder/addExplicit
       {
         int uWood = in.read_long ();
         int uMarble = in.read_long ();
         int uWine = in.read_long ();
         int uCrytsal = in.read_long ();
         int uBrimstone = in.read_long ();
         Consumers._RessourceHolder $result = null;
         $result = this.addExplicit (uWood, uMarble, uWine, uCrytsal, uBrimstone);
         out = $rh.createReply();
         Consumers._RessourceHolderHelper.write (out, $result);
         break;
       }

       case 14:  // Consumers/_RessourceHolder/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Consumers/RessourceHolder:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class __RessourceHolderImplBase
