package Consumers;


/**
* Consumers/_RemoteConsumerImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Piatok, 2017, apríla 28 16:53:03 CEST
*/

public abstract class _RemoteConsumerImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Consumers.RemoteConsumer, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _RemoteConsumerImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_idConsumer", new java.lang.Integer (0));
    _methods.put ("_get_readyToGo", new java.lang.Integer (1));
    _methods.put ("_get_manualMode", new java.lang.Integer (2));
    _methods.put ("_get_resCurrent", new java.lang.Integer (3));
    _methods.put ("_get_resTarget", new java.lang.Integer (4));
    _methods.put ("_get_personality", new java.lang.Integer (5));
    _methods.put ("_get_gameOver", new java.lang.Integer (6));
    _methods.put ("setIdConsumer", new java.lang.Integer (7));
    _methods.put ("setReadyToGo", new java.lang.Integer (8));
    _methods.put ("setManualMode", new java.lang.Integer (9));
    _methods.put ("setResCurrent", new java.lang.Integer (10));
    _methods.put ("setResTarget", new java.lang.Integer (11));
    _methods.put ("setPersonality", new java.lang.Integer (12));
    _methods.put ("setGameOver", new java.lang.Integer (13));
    _methods.put ("updateRessources", new java.lang.Integer (14));
    _methods.put ("finished", new java.lang.Integer (15));
    _methods.put ("toString", new java.lang.Integer (16));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Consumers/RemoteConsumer/_get_idConsumer
       {
         String $result = null;
         $result = this.idConsumer ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Consumers/RemoteConsumer/_get_readyToGo
       {
         boolean $result = false;
         $result = this.readyToGo ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Consumers/RemoteConsumer/_get_manualMode
       {
         boolean $result = false;
         $result = this.manualMode ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Consumers/RemoteConsumer/_get_resCurrent
       {
         Consumers.VectorRessource $result = null;
         $result = this.resCurrent ();
         out = $rh.createReply();
         Consumers.VectorRessourceHelper.write (out, $result);
         break;
       }

       case 4:  // Consumers/RemoteConsumer/_get_resTarget
       {
         Consumers.VectorRessource $result = null;
         $result = this.resTarget ();
         out = $rh.createReply();
         Consumers.VectorRessourceHelper.write (out, $result);
         break;
       }

       case 5:  // Consumers/RemoteConsumer/_get_personality
       {
         char $result = (char)0;
         $result = this.personality ();
         out = $rh.createReply();
         out.write_char ($result);
         break;
       }

       case 6:  // Consumers/RemoteConsumer/_get_gameOver
       {
         boolean $result = false;
         $result = this.gameOver ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // Consumers/RemoteConsumer/setIdConsumer
       {
         String id = in.read_string ();
         this.setIdConsumer (id);
         out = $rh.createReply();
         break;
       }

       case 8:  // Consumers/RemoteConsumer/setReadyToGo
       {
         boolean status = in.read_boolean ();
         this.setReadyToGo (status);
         out = $rh.createReply();
         break;
       }

       case 9:  // Consumers/RemoteConsumer/setManualMode
       {
         boolean mode = in.read_boolean ();
         this.setManualMode (mode);
         out = $rh.createReply();
         break;
       }

       case 10:  // Consumers/RemoteConsumer/setResCurrent
       {
         Consumers.VectorRessource current = Consumers.VectorRessourceHelper.read (in);
         this.setResCurrent (current);
         out = $rh.createReply();
         break;
       }

       case 11:  // Consumers/RemoteConsumer/setResTarget
       {
         Consumers.VectorRessource target = Consumers.VectorRessourceHelper.read (in);
         this.setResTarget (target);
         out = $rh.createReply();
         break;
       }

       case 12:  // Consumers/RemoteConsumer/setPersonality
       {
         char personality = in.read_char ();
         this.setPersonality (personality);
         out = $rh.createReply();
         break;
       }

       case 13:  // Consumers/RemoteConsumer/setGameOver
       {
         boolean over = in.read_boolean ();
         this.setGameOver (over);
         out = $rh.createReply();
         break;
       }

       case 14:  // Consumers/RemoteConsumer/updateRessources
       {
         Consumers.VectorRessource acquired = Consumers.VectorRessourceHelper.read (in);
         this.updateRessources (acquired);
         out = $rh.createReply();
         break;
       }

       case 15:  // Consumers/RemoteConsumer/finished
       {
         boolean $result = false;
         $result = this.finished ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 16:  // Consumers/RemoteConsumer/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Consumers/RemoteConsumer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _RemoteConsumerImplBase
