package Consumers;


/**
* Consumers/_RessourceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Streda, 2017, apríla 26 11:26:04 CEST
*/

public interface _RessourceHolder extends _RessourceHolderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface _RessourceHolder
