package Consumers;

/**
* Consumers/_RessourceHolderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Streda, 2017, apríla 26 11:26:04 CEST
*/

public final class _RessourceHolderHolder implements org.omg.CORBA.portable.Streamable
{
  public Consumers._RessourceHolder value = null;

  public _RessourceHolderHolder ()
  {
  }

  public _RessourceHolderHolder (Consumers._RessourceHolder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Consumers._RessourceHolderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Consumers._RessourceHolderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Consumers._RessourceHolderHelper.type ();
  }

}
