package Consumers;


/**
* Consumers/_RessourceHolderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Streda, 2017, apríla 26 11:26:04 CEST
*/

abstract public class _RessourceHolderHelper
{
  private static String  _id = "IDL:Consumers/RessourceHolder:1.0";

  public static void insert (org.omg.CORBA.Any a, Consumers._RessourceHolder that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Consumers._RessourceHolder extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Consumers._RessourceHolderHelper.id (), "RessourceHolder");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Consumers._RessourceHolder read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (__RessourceHolderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Consumers._RessourceHolder value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Consumers._RessourceHolder narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Consumers._RessourceHolder)
      return (Consumers._RessourceHolder)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Consumers.__RessourceHolderStub stub = new Consumers.__RessourceHolderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Consumers._RessourceHolder unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Consumers._RessourceHolder)
      return (Consumers._RessourceHolder)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Consumers.__RessourceHolderStub stub = new Consumers.__RessourceHolderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
