package Consumers;


/**
* Consumers/_RessourceHolderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Streda, 2017, apríla 26 11:26:04 CEST
*/

public interface _RessourceHolderOperations 
{
  int resWood ();
  int resMarble ();
  int resWine ();
  int resCrystal ();
  int resBrimstone ();
  void setWood (int units);
  void setMarble (int units);
  void setWine (int units);
  void setCrystal (int units);
  void setBrimstone (int units);
  void setAll (int uWood, int uMarble, int uWine, int uCrytsal, int uBrimstone);
  int compare (Consumers._RessourceHolder toBeCompared);
  Consumers._RessourceHolder add (Consumers._RessourceHolder operand);
  Consumers._RessourceHolder addExplicit (int uWood, int uMarble, int uWine, int uCrytsal, int uBrimstone);
  String _toString ();
} // interface _RessourceHolderOperations
