package Consumers;


/**
* Consumers/_VectorRessourceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Pondelok, 2017, mája 1 21:03:36 CEST
*/

public abstract class _VectorRessourceImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Consumers.VectorRessource, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _VectorRessourceImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_resWood", new java.lang.Integer (0));
    _methods.put ("_get_resMarble", new java.lang.Integer (1));
    _methods.put ("setWood", new java.lang.Integer (2));
    _methods.put ("setMarble", new java.lang.Integer (3));
    _methods.put ("setAll", new java.lang.Integer (4));
    _methods.put ("compare", new java.lang.Integer (5));
    _methods.put ("add", new java.lang.Integer (6));
    _methods.put ("subtract", new java.lang.Integer (7));
    _methods.put ("addExplicit", new java.lang.Integer (8));
    _methods.put ("toString", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Consumers/VectorRessource/_get_resWood
       {
         int $result = (int)0;
         $result = this.resWood ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Consumers/VectorRessource/_get_resMarble
       {
         int $result = (int)0;
         $result = this.resMarble ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Consumers/VectorRessource/setWood
       {
         int units = in.read_long ();
         this.setWood (units);
         out = $rh.createReply();
         break;
       }

       case 3:  // Consumers/VectorRessource/setMarble
       {
         int units = in.read_long ();
         this.setMarble (units);
         out = $rh.createReply();
         break;
       }

       case 4:  // Consumers/VectorRessource/setAll
       {
         int uWood = in.read_long ();
         int uMarble = in.read_long ();
         this.setAll (uWood, uMarble);
         out = $rh.createReply();
         break;
       }

       case 5:  // Consumers/VectorRessource/compare
       {
         Consumers.VectorRessource toBeCompared = Consumers.VectorRessourceHelper.read (in);
         boolean $result = false;
         $result = this.compare (toBeCompared);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // Consumers/VectorRessource/add
       {
         Consumers.VectorRessource operand = Consumers.VectorRessourceHelper.read (in);
         this.add (operand);
         out = $rh.createReply();
         break;
       }

       case 7:  // Consumers/VectorRessource/subtract
       {
         Consumers.VectorRessource operand = Consumers.VectorRessourceHelper.read (in);
         this.subtract (operand);
         out = $rh.createReply();
         break;
       }

       case 8:  // Consumers/VectorRessource/addExplicit
       {
         int uWood = in.read_long ();
         int uMarble = in.read_long ();
         this.addExplicit (uWood, uMarble);
         out = $rh.createReply();
         break;
       }

       case 9:  // Consumers/VectorRessource/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Consumers/VectorRessource:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _VectorRessourceImplBase
