package Consumers;


/**
* Consumers/RemoteConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Pondelok, 2017, mája 1 21:03:36 CEST
*/

public interface RemoteConsumer extends RemoteConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteConsumer
