package Consumers;


/**
* Consumers/VectorRessourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Pondelok, 2017, mája 1 16:28:02 CEST
*/

public interface VectorRessourceOperations 
{
  int resWood ();
  int resMarble ();
  void setWood (int units);
  void setMarble (int units);
  void setAll (int uWood, int uMarble);
  boolean compare (Consumers.VectorRessource toBeCompared);
  void add (Consumers.VectorRessource operand);
  void subtract (Consumers.VectorRessource operand);
  void addExplicit (int uWood, int uMarble);
  String _toString ();
} // interface VectorRessourceOperations
