package Consumers;

/**
* Consumers/VectorRessourceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Piatok, 2017, apríla 28 16:53:03 CEST
*/

public final class VectorRessourceHolder implements org.omg.CORBA.portable.Streamable
{
  public Consumers.VectorRessource value = null;

  public VectorRessourceHolder ()
  {
  }

  public VectorRessourceHolder (Consumers.VectorRessource initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Consumers.VectorRessourceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Consumers.VectorRessourceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Consumers.VectorRessourceHelper.type ();
  }

}
