package Consumers;


/**
* Consumers/VectorRessourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Piatok, 2017, apríla 28 16:53:03 CEST
*/

public interface VectorRessourceOperations 
{
  int resWood ();
  int resMarble ();
  int resWine ();
  int resCrystal ();
  int resBrimstone ();
  void setWood (int units);
  void setMarble (int units);
  void setWine (int units);
  void setCrystal (int units);
  void setBrimstone (int units);
  void setAll (int uWood, int uMarble, int uWine, int uCrystal, int uBrimstone);
  boolean compare (Consumers.VectorRessource toBeCompared);
  void add (Consumers.VectorRessource operand);
  void subtract (Consumers.VectorRessource operand);
  void addExplicit (int uWood, int uMarble, int uWine, int uCrystal, int uBrimstone);
  String _toString ();
} // interface VectorRessourceOperations
