package Consumers;


/**
* Consumers/VectorRessource.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Piatok, 2017, apríla 28 16:53:03 CEST
*/

public interface VectorRessource extends VectorRessourceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VectorRessource
