package Consumers;


/**
* Consumers/VectorRessource.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RemoteConsumer.idl
* Sobota, 2017, apríla 29 10:59:02 CEST
*/

public interface VectorRessource extends VectorRessourceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VectorRessource
