@echo Cleaning IOR containers...
@echo Removing Consumers...
@del /F ..\consumers.drg
@echo Removing Producers...
@del /F ..\wood_producers.drg
@del /F ..\marble_producers.drg
@del /F ..\crystal_producers.drg
@echo Cleaning finished