module Producers
{
	enum RessourceType 
	{
		WOOD, MARBLE, WINE, CRYSTAL, BRIMSTONE
	};

	interface RemoteProducer
	{
		readonly attribute RessourceType type;
		readonly attribute long id;
		readonly attribute long count;
		readonly attribute long step;
		readonly attribute long refillFrequence;
		readonly attribute boolean readyToGo;

		void setReadyToGo(in boolean status);

		void pretype(in RessourceType type);
		void generate();
		long acquire(in long units, in char personality);
	};
};
