module Consumers
{
    interface VectorRessource
    {
        readonly attribute long resWood;
        readonly attribute long resMarble;
        readonly attribute long resWine;
        readonly attribute long resCrystal;
        readonly attribute long resBrimstone;

        void setWood(in long units);
        void setMarble(in long units);
        void setWine(in long units);
        void setCrystal(in long units);
        void setBrimstone(in long units);
        void setAll(in long uWood, in long uMarble, in long uWine, in long uCrystal, in long uBrimstone);

        boolean compare(in VectorRessource toBeCompared);
        void add(in VectorRessource operand);
        void subtract(in VectorRessource operand);
        void addExplicit(in long uWood, in long uMarble, in long uWine, in long uCrystal, in long uBrimstone);

        string toString();
    };

    interface RemoteConsumer
    {
        readonly attribute string idConsumer;
        readonly attribute boolean readyToGo;
        readonly attribute boolean manualMode;
        readonly attribute VectorRessource resCurrent;
        readonly attribute VectorRessource resTarget;
        readonly attribute char personality;
        readonly attribute boolean gameOver;

        void setIdConsumer(in string id);
        void setReadyToGo(in boolean status);
        void setManualMode(in boolean mode);
        void setResCurrent(in VectorRessource current);
        void setResTarget(in VectorRessource target);
        void setPersonality(in char personality);
        void setGameOver(in boolean over);

        void updateRessources(in VectorRessource acquired);
        boolean finished();

        string toString();
    };
};
