module Producers
{
	enum RessourceType 
	{
		WOOD, MARBLE, WINE, CRYSTAL, BRIMSTONE
	};

	interface RemoteProducer
	{
		readonly attribute RessourceType type;
		readonly attribute long id;
		readonly attribute long count;
		readonly attribute long step;
		readonly attribute long refillFrequence; 

		void pretype(in RessourceType type);
		void generate();
		boolean acquire(in long count);
	};
};
