module Producers
{
	enum RessourceType 
	{
		WOOD, MARBLE, CRYSTAL
	};

	interface RemoteProducer
	{
		readonly attribute RessourceType type;
		readonly attribute long id;
		readonly attribute long count;
		readonly attribute long step;
		readonly attribute long refillFrequence;
		readonly attribute boolean readyToGo;
		readonly attribute boolean infiniteRessources;

		void setReadyToGo(in boolean status);
		void setInfiniteRessources(in boolean property);

		void pretype(in RessourceType type);
		void generate();
		long acquire(in long units, in char personality);

		string toString();
	};
};
