package Ressources;


/**
* Ressources/RessourceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

abstract public class RessourceHelper
{
  private static String  _id = "IDL:Ressources/Ressource:1.0";

  public static void insert (org.omg.CORBA.Any a, Ressources.Ressource that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Ressources.Ressource extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Ressources.RessourceHelper.id (), "Ressource");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Ressources.Ressource read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RessourceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Ressources.Ressource value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Ressources.Ressource narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Ressources.Ressource)
      return (Ressources.Ressource)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Ressources._RessourceStub stub = new Ressources._RessourceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Ressources.Ressource unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Ressources.Ressource)
      return (Ressources.Ressource)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Ressources._RessourceStub stub = new Ressources._RessourceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
