package Ressources;


/**
* Ressources/Ressource.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

public interface Ressource extends RessourceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ressource
