package Ressources;

/**
* Ressources/RessourceTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

public final class RessourceTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public Ressources.RessourceType value = null;

  public RessourceTypeHolder ()
  {
  }

  public RessourceTypeHolder (Ressources.RessourceType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ressources.RessourceTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ressources.RessourceTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ressources.RessourceTypeHelper.type ();
  }

}
