package Ressources;


/**
* Ressources/RessourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

public interface RessourceOperations 
{
  Ressources.RessourceType type ();
  int count ();
  int step ();
  void pretype (Ressources.RessourceType type);
  void generate (int count);
  boolean acquire (int count);
} // interface RessourceOperations
