package Ressources;


/**
* Ressources/RessourceType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ressource.idl
* Pondelok, 2017, apríla 17 17:54:20 CEST
*/

public class RessourceType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static Ressources.RessourceType[] __array = new Ressources.RessourceType [__size];

  public static final int _WOOD = 0;
  public static final Ressources.RessourceType WOOD = new Ressources.RessourceType(_WOOD);
  public static final int _MARBLE = 1;
  public static final Ressources.RessourceType MARBLE = new Ressources.RessourceType(_MARBLE);
  public static final int _WINE = 2;
  public static final Ressources.RessourceType WINE = new Ressources.RessourceType(_WINE);
  public static final int _CRYSTAL = 3;
  public static final Ressources.RessourceType CRYSTAL = new Ressources.RessourceType(_CRYSTAL);
  public static final int _BRIMSTONE = 4;
  public static final Ressources.RessourceType BRIMSTONE = new Ressources.RessourceType(_BRIMSTONE);

  public int value ()
  {
    return __value;
  }

  public static Ressources.RessourceType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RessourceType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class RessourceType
